source "https://rubygems.org"
ruby '>= 2.7', '< 3.1'

#DSL for quickly creating web applictions 
gem "sinatra", "~> 2.1"

#An object relational mapper
gem "activerecord", "~> 6.1"

# A fast and simple web server
gem "thin", "~> 1.8"

# Rack middleware. Used specifically for parsing the request body into params.
gem "rack-contrib", "~> 2.3"

# More Rack middleware! Used to handle CORS requests
gem "rack-cors", "~> 1.1"

#Configures common Rake tasks for working with Active Record
gem "sinatra-activerecord", "~> 2.0"

#Run Common tasks from the command line
gem "rake", "~> 13.0"

# Provides functionality to interact with a SQLite3 database
gem "sqlite3", "~> 1.4"

# Require all files in a folder
gem "require_all", "~> 3.0"

# Automatically reload when there are changes
gem "rerun"

gem 'pry'

